version: '3'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    env_file:
    - .env
    # environment:
    #   DATABASE_URL: postgres://neo:babe@postgres:5432/url_shortner?sslmode=disable
    #   DATABASE_URL_TEST: postgres://neo:babe@postgres:5432/url_shortner_test?sslmode=disable
    networks:
      - app_network

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: url_shortner
      POSTGRES_USER: neo
      POSTGRES_PASSWORD: babe
    ports:
      - "5433:5432"

    networks:
      - app_network

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6380:6379"
    networks:
      - app_network

networks:
  app_network:

